### ISSUE TITLE
merge this into contrib packages repository?

### ISSUE THREAD

**Issue by anarcat** [Gr4ffy/lede-cups#6]
I do not understand why OpenWRT lost cups support. I have found that it was lost somewhere after attitude adjustment (12.09) and the [OpenWRT cups documentation](https://openwrt.org/docs/guide-user/services/print_server/cups.server) refers to this repository for "LEDE images", which, presumably, means that anything released after the LEDE/OpenWRT fork/remerge is missing cups as well.

There was work in the packages repository to import cups (in https://github.com/openwrt/packages/pull/1452, https://github.com/openwrt/packages/pull/1453, https://github.com/openwrt/packages/pull/1454, https://github.com/openwrt/packages/issues/2407) but that was blocked by @psycho-nico who said, in 2016, that he was already working on importing cups from the [old packages repository](https://git.archive.openwrt.org/?p=packages.git;a=tree;f=net/cups;hb=HEAD).

So is there any reason for this repository to stay standalone? Shouldn't this be merged with the [main repository](https://github.com/openwrt/packages)?

**Comment by anarcat** [comment]
I have opened a match issue upstream in https://github.com/openwrt/packages/issues/7016

**Comment by OhSoGood** [comment]
@Gr4ffy : I would really appreciate if you find time to merge this into openwrt's official repo. Cups is the only missing package I need to migrate the routers of my family to openwrt 18.06.x.

Thanks in advance for your time & effort!

**Comment by StarUnderNight** [comment]
hello,I come across a problem that it needs username and password  when I do as your approach.
like this:
Updating feed 'cups' from 'https://github.com/Gr4ffy/led-cups.git'...
正克隆到 './feeds/cups/...
Username for 'https://github.com':
